### PR TITLE
Fix TimeZone mappings for Windows Phone and Unity

### LINKED ISSUE #138: ParseInstallation.CurrentInstallation.SaveAsync() not working when device is not in English.
When I try to call the method:

    ParseInstallation.CurrentInstallation.SaveAsync();

on a phone that is configured with a language other than English

I get an InvalidOperationException: "Cannot change the `timeZone` property of a `_Installation` object."

This occurs because Windows Phone is returning a localized string for the local timezone information. Because that string is localized it won't find a match on the `TimeZoneNameMap` dictionary, thus returning null.

Returning null will make the SDK try to remove the `timeZone` property from the `Installation` object.

*UPDATE*: I was trying to run this in a previous version, so I went and checked if there was a newer version and installed the 1.6.2 version out of NuGet.

This version allows the SDK to set the `timeZone` to null and does not try to remove the property, mostly because you guys changed the `SetIfDifferent` method.
But this raises an exception anyway. When sending the data to the Parse servers I now get "BadRequest", and I think the problem is still the same.

Can you please fix this?

### PR DESCRIPTION
**Pull request by richardjrossiii**
This was causing installation saves to fail when not on english locale.

For real, this time.

Fixes #138.

### CODE REVIEW

File: Parse/Public/ParseInstallation.cs [hunk 1]
```diff
@@ -352,5 +352,26 @@ public ParseInstallation()
...
+    /// This is a mapping of odd TimeZone offsets to their respective IANA codes across the world.
+    /// This list was compiled from painstakingly pouring over the information available at
+    /// https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
+    /// </summary>
+    internal static readonly Dictionary<TimeSpan, String> TimeZoneOffsetMap = new Dictionary<TimeSpan, string>() {
+      { new TimeSpan(12, 45, 0), "Pacific/Chatham" },
+      { new TimeSpan(10, 30, 0), "Australia/Lord_Howe" },
+      { new TimeSpan(9, 30, 0),  "Australia/Adelaide" },
+      { new TimeSpan(8, 45, 0), "Australia/Eucla" },
+      { new TimeSpan(8, 30, 0), "Asia/Pyongyang" }, // Parse in North Korea confirmed.
```
Comment (hallucinogen) [inline Parse/Public/ParseInstallation.cs]: +1

**Comment by hallucinogen** [comment]
Looks good to me.
