### PR TITLE
Make `SetIfDifferent` no longer check if a key is mutable.

### LINKED ISSUE #40: Unity SDK, iOS build. "Cannot change the appIdentifier" error
Hi guys!

I have a problem with Unity SDK when launching XCode project:

```
InvalidOperationException: Cannot change the `appIdentifier` property of a `_Installation` object.
  at Parse.ParseObject.CheckKeyIsMutable (System.String key) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.Remove (System.String key) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.SetIfDifferent[String] (System.String key, System.String value) [0x00000] in <filename unknown>:0 
  at Parse.ParseInstallation.SaveAsync (System.Threading.Tasks.Task toAwait, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject+<>c__DisplayClass3a.<SaveAsync>b__39 (System.Threading.Tasks.Task toAwait) [0x00000] in <filename unknown>:0 
  at Parse.Internal.TaskQueue.Enqueue[Task] (System.Func`2 taskStart, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.SaveAsync (CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.SaveAsync () [0x00000] in <filename unknown>:0 
  at Parse.ParseInitializeBehaviour.<Awake>b__0 (System.Byte[] deviceToken) [0x00000] in <filename unknown>:0 
  at Parse.PlatformHooks+<>c__DisplayClass28.<RegisterDeviceTokenRequest>b__26 () [0x00000] in <filename unknown>:0 
  at Parse.PlatformHooks+<RunDispatcher>d__2e.MoveNext () [0x00000] in <filename unknown>:0 
```

It's not a fatal error - app still working but I think it shouldn't be there.
All that I doing is:

``` 
UnityEngine.iOS.NotificationServices.RegisterForNotifications(UnityEngine.iOS.NotificationType.Alert |
																UnityEngine.iOS.NotificationType.Badge |
																UnityEngine.iOS.NotificationType.Sound);

### PR DESCRIPTION
**Pull request by richardjrossiii**
This would cause issues when updating an installation. By forcing removal of a key using an operation, we no longer check for children who override `IsMutableForKey`.

Fixes #40, and probably several others.

cc @grantland @hallucinogen

### CODE REVIEW

File: Parse/ParseInstallation.cs [hunk 1]
```diff
@@ -220,13 +220,13 @@ public ParseInstallation()
...
       Task platformHookTask = null;
       if (CurrentInstallationController.IsCurrent(this)) {
-        SetIfDifferent("deviceType", ParseClient.PlatformHooks.DeviceType);
-        SetIfDifferent("timeZone", ParseClient.PlatformHooks.DeviceTimeZone);
-        SetIfDifferent("localeIdentifier", GetLocaleIdentifier());
-        SetIfDifferent("parseVersion", GetParseVersion().ToString());
-        SetIfDifferent("appVersion", ParseClient.PlatformHooks.AppBuildVersion);
-        SetIfDifferent("appIdentifier", ParseClient.PlatformHooks.AppIdentifier);
-        SetIfDifferent("appName", ParseClient.PlatformHooks.AppName);
+        ForceSetIfDifferent("deviceType", ParseClient.PlatformHooks.DeviceType);
```
Comment (hallucinogen) [inline Parse/ParseInstallation.cs]: `SetIfDifferent` will not check for mutability. https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse/ParseObject.cs#L1238

I'm not sure this is the right fix.

Comment (richardjrossiii) [inline Parse/ParseInstallation.cs]: It does check for mutability when it calls `Remove`, though.I guess we can change each of these `SetIfDifferentCalls` and bound them by a null check on the value, although I'm not certain that makes a ton of sense (we could end up with really stale values).

Comment (hallucinogen) [inline Parse/ParseInstallation.cs]: I think the correct solution for this would be to refactor `SetIfDifferent` so that it also forces `Remove`, and not make another `ForceSetIfDifferent`. `SetIfDifferent` by definition should force update.

**Comment by richardjrossiii** [comment]
PR updated.

**Comment by hallucinogen** [comment]
Perfecto
